# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Etienne Rivet
tagline:          'Personal Blog'
description:      'Follow me on my random exploration of the digital world.'
url:              https://www.linkedin.com/in/etiennerivet/
baseurl:          /

author:
  name:           'Etienne Rivet'
  url:            https://www.linkedin.com/in/etiennerivet/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/erivet
